apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: go-demo-9
build:
  local: {}
  artifacts:
  - image: go-demo-9
    docker: {}
  tagPolicy:
    sha256: {} 
profiles:
- name: remote
  build:
    cluster:
      namespace: my-dev
      dockerConfig:
        path: ~/.docker/config.json
    artifacts:
    - image: go-demo-9
      kaniko: {}
    tagPolicy:
      dateTime:
        format: 2006-01-02
