apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: go-demo-9
build:
  local:
    push: false
  artifacts:
    - image: go-demo-9
      docker: {}
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: go-demo-9
        namespace: dev
        createNamespace: true
        chartPath: charts/go-demo-9
        wait: true
        valuesFiles:
          - charts/dev/values.yaml
        version: 0.0.1
        setValueTemplates:
          ingress.host: "{{ .ADDR }}"
          image.repository: "{{.IMAGE_REPO_go_demo_9}}"
          image.tag: "{{.IMAGE_TAG_go_demo_9}}"
    flags:
      upgrade:
        - --install
